<?php

use Illuminate\Database\Seeder;

class CurrencySeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \App\Currency::truncate();
        \App\Currency::insert([
            ['currency' => 'Afghani', 'short_description' => 'AFN', 'country' => 'Afghanistan', 'rate' => 0],
            ['currency' => 'Euro', 'short_description' => 'EUR', 'country' => 'Åland Islands', 'rate' => 0],
            ['currency' => 'Lek', 'short_description' => 'ALL', 'country' => 'Albania', 'rate' => 0],
            ['currency' => 'Algerian Dinar', 'short_description' => 'DZD', 'country' => 'Algeria', 'rate' => 0],
            ['currency' => 'US Dollar', 'short_description' => 'USD', 'country' => 'American Samoa', 'rate' => 0],
            ['currency' => 'Euro', 'short_description' => 'EUR', 'country' => 'Andorra', 'rate' => 0],
            ['currency' => 'Kwanza', 'short_description' => 'AOA', 'country' => 'Angola', 'rate' => 0],
            ['currency' => 'East Caribbean Dollar', 'short_description' => 'XCD', 'country' => 'Anguilla', 'rate' => 0],
            ['currency' => 'East Caribbean Dollar', 'short_description' => 'XCD', 'country' => 'Antigua And Barbuda', 'rate' => 0],
            ['currency' => 'Argentine Peso', 'short_description' => 'ARS', 'country' => 'Argentina', 'rate' => 0],
            ['currency' => 'Armenian Dram', 'short_description' => 'AMD', 'country' => 'Armenia', 'rate' => 0],
            ['currency' => 'Aruban Florin', 'short_description' => 'AWG', 'country' => 'Aruba', 'rate' => 0],
            ['currency' => 'Australian Dollar', 'short_description' => 'AUD', 'country' => 'Australia', 'rate' => 0],
            ['currency' => 'Euro', 'short_description' => 'EUR', 'country' => 'Austria', 'rate' => 0],
            ['currency' => 'Azerbaijan Manat', 'short_description' => 'AZN', 'country' => 'Azerbaijan', 'rate' => 0],
            ['currency' => 'Bahamian Dollar', 'short_description' => 'BSD', 'country' => 'Bahamas (The)', 'rate' => 0],
            ['currency' => 'Bahraini Dinar', 'short_description' => 'BHD', 'country' => 'Bahrain', 'rate' => 0],
            ['currency' => 'Taka', 'short_description' => 'BDT', 'country' => 'Bangladesh', 'rate' => 0],
            ['currency' => 'Barbados Dollar', 'short_description' => 'BBD', 'country' => 'BARBADOS', 'rate' => 0],
            ['currency' => 'Belarusian Ruble', 'short_description' => 'BYN', 'country' => 'Belarus', 'rate' => 0],
            ['currency' => 'Euro', 'short_description' => 'EUR', 'country' => 'Belgium', 'rate' => 0],
            ['currency' => 'Belize Dollar', 'short_description' => 'BZD', 'country' => 'Belize', 'rate' => 0],
            ['currency' => 'CFA Franc BCEAO', 'short_description' => 'XOF', 'country' => 'Benin', 'rate' => 0],
            ['currency' => 'Bermudian Dollar', 'short_description' => 'BMD', 'country' => 'Bermuda', 'rate' => 0],
            ['currency' => 'Indian Rupee', 'short_description' => 'INR', 'country' => 'Bhutan', 'rate' => 0],
            ['currency' => 'Ngultrum', 'short_description' => 'BTN', 'country' => 'Bhutan', 'rate' => 0],
            ['currency' => 'Boliviano', 'short_description' => 'BOB', 'country' => 'Bolivia (Plurinational State Of)', 'rate' => 0],
            ['currency' => 'Mvdol', 'short_description' => 'BOV', 'country' => 'Bolivia (Plurinational State Of)', 'rate' => 0],
            ['currency' => 'US Dollar', 'short_description' => 'USD', 'country' => 'Bonaire, Sint Eustatius And Saba', 'rate' => 0],
            ['currency' => 'Convertible Mark', 'short_description' => 'BAM', 'country' => 'Bosnia And Herzegovina', 'rate' => 0],
            ['currency' => 'Pula', 'short_description' => 'BWP', 'country' => 'Botswana', 'rate' => 0],
            ['currency' => 'Norwegian Krone', 'short_description' => 'NOK', 'country' => 'Bouvet Island', 'rate' => 0],
            ['currency' => 'Brazilian Real', 'short_description' => 'BRL', 'country' => 'Brazil', 'rate' => 0],
            ['currency' => 'US Dollar', 'short_description' => 'USD', 'country' => 'British Indian Ocean Territory (The)', 'rate' => 0],
            ['currency' => 'Brunei Dollar', 'short_description' => 'BND', 'country' => 'Brunei Darussalam', 'rate' => 0],
            ['currency' => 'Bulgarian Lev', 'short_description' => 'BGN', 'country' => 'Bulgaria', 'rate' => 0],
            ['currency' => 'CFA Franc BCEAO', 'short_description' => 'XOF', 'country' => 'Burkina Faso', 'rate' => 0],
            ['currency' => 'Burundi Franc', 'short_description' => 'BIF', 'country' => 'Burundi', 'rate' => 0],
            ['currency' => 'Cabo Verde Escudo', 'short_description' => 'CVE', 'country' => 'Cabo Verde', 'rate' => 0],
            ['currency' => 'Riel', 'short_description' => 'KHR', 'country' => 'Cambodia', 'rate' => 0],
            ['currency' => 'CFA Franc BEAC', 'short_description' => 'XAF', 'country' => 'Cameroon', 'rate' => 0],
            ['currency' => 'Canadian Dollar', 'short_description' => 'CAD', 'country' => 'Canada', 'rate' => 0],
            ['currency' => 'Cayman Islands Dollar', 'short_description' => 'KYD', 'country' => 'Cayman Islands (The)', 'rate' => 0],
            ['currency' => 'CFA Franc BEAC', 'short_description' => 'XAF', 'country' => 'Central African Republic (The)', 'rate' => 0],
            ['currency' => 'CFA Franc BEAC', 'short_description' => 'XAF', 'country' => 'Chad', 'rate' => 0],
            ['currency' => 'Chilean Peso', 'short_description' => 'CLP', 'country' => 'Chile', 'rate' => 0],
            ['currency' => 'Unidad de Fomento', 'short_description' => 'CLF', 'country' => 'Chile', 'rate' => 0],
            ['currency' => 'Yuan Renminbi', 'short_description' => 'CNY', 'country' => 'China', 'rate' => 0],
            ['currency' => 'Australian Dollar', 'short_description' => 'AUD', 'country' => 'Christmas Island', 'rate' => 0],
            ['currency' => 'Australian Dollar', 'short_description' => 'AUD', 'country' => 'Cocos (Keeling) Islands (The)', 'rate' => 0],
            ['currency' => 'Colombian Peso', 'short_description' => 'COP', 'country' => 'Colombia', 'rate' => 0],
            ['currency' => 'Unidad de Valor Real', 'short_description' => 'COU', 'country' => 'Colombia', 'rate' => 0],
            ['currency' => 'Comorian Franc ', 'short_description' => 'KMF', 'country' => 'Comoros (The)', 'rate' => 0],
            ['currency' => 'Congolese Franc', 'short_description' => 'CDF', 'country' => 'Congo (The Democratic Republic Of The)', 'rate' => 0],
            ['currency' => 'CFA Franc BEAC', 'short_description' => 'XAF', 'country' => 'Congo (The)', 'rate' => 0],
            ['currency' => 'New Zealand Dollar', 'short_description' => 'NZD', 'country' => 'Cook Islands (The)', 'rate' => 0],
            ['currency' => 'Costa Rican Colon', 'short_description' => 'CRC', 'country' => 'Costa Rica', 'rate' => 0],
            ['currency' => 'CFA Franc BCEAO', 'short_description' => 'XOF', 'country' => 'Côte D\'ivoire', 'rate' => 0],
            ['currency' => 'Kuna', 'short_description' => 'HRK', 'country' => 'Croatia', 'rate' => 0],
            ['currency' => 'Cuban Peso', 'short_description' => 'CUP', 'country' => 'Cuba', 'rate' => 0],
            ['currency' => 'Peso Convertible', 'short_description' => 'CUC', 'country' => 'Cuba', 'rate' => 0],
            ['currency' => 'Netherlands Antillean Guilder', 'short_description' => 'ANG', 'country' => 'Curaçao', 'rate' => 0],
            ['currency' => 'Euro', 'short_description' => 'EUR', 'country' => 'Cyprus', 'rate' => 0],
            ['currency' => 'Czech Koruna', 'short_description' => 'CZK', 'country' => 'Czechia', 'rate' => 0],
            ['currency' => 'Danish Krone', 'short_description' => 'DKK', 'country' => 'Denmark', 'rate' => 0],
            ['currency' => 'Djibouti Franc', 'short_description' => 'DJF', 'country' => 'Djibouti', 'rate' => 0],
            ['currency' => 'East Caribbean Dollar', 'short_description' => 'XCD', 'country' => 'Dominica', 'rate' => 0],
            ['currency' => 'Dominican Peso', 'short_description' => 'DOP', 'country' => 'Dominican Republic (The)', 'rate' => 0],
            ['currency' => 'US Dollar', 'short_description' => 'USD', 'country' => 'Ecuador', 'rate' => 0],
            ['currency' => 'Egyptian Pound', 'short_description' => 'EGP', 'country' => 'Egypt', 'rate' => 0],
            ['currency' => 'El Salvador Colon', 'short_description' => 'SVC', 'country' => 'El Salvador', 'rate' => 0],
            ['currency' => 'US Dollar', 'short_description' => 'USD', 'country' => 'El Salvador', 'rate' => 0],
            ['currency' => 'CFA Franc BEAC', 'short_description' => 'XAF', 'country' => 'Equatorial Guinea', 'rate' => 0],
            ['currency' => 'Nakfa', 'short_description' => 'ERN', 'country' => 'Eritrea', 'rate' => 0],
            ['currency' => 'Euro', 'short_description' => 'EUR', 'country' => 'Estonia', 'rate' => 0],
            ['currency' => 'Ethiopian Birr', 'short_description' => 'ETB', 'country' => 'Ethiopia', 'rate' => 0],
            ['currency' => 'Euro', 'short_description' => 'EUR', 'country' => 'European Union', 'rate' => 0],
            ['currency' => 'Falkland Islands Pound', 'short_description' => 'FKP', 'country' => 'Falkland Islands (The) [Malvinas]', 'rate' => 0],
            ['currency' => 'Danish Krone', 'short_description' => 'DKK', 'country' => 'Faroe Islands (The)', 'rate' => 0],
            ['currency' => 'Fiji Dollar', 'short_description' => 'FJD', 'country' => 'Fiji', 'rate' => 0],
            ['currency' => 'Euro', 'short_description' => 'EUR', 'country' => 'Finland', 'rate' => 0],
            ['currency' => 'Euro', 'short_description' => 'EUR', 'country' => 'France', 'rate' => 0],
            ['currency' => 'Euro', 'short_description' => 'EUR', 'country' => 'French Guiana', 'rate' => 0],
            ['currency' => 'CFP Franc', 'short_description' => 'XPF', 'country' => 'French Polynesia', 'rate' => 0],
            ['currency' => 'Euro', 'short_description' => 'EUR', 'country' => 'French Southern Territories (The)', 'rate' => 0],
            ['currency' => 'CFA Franc BEAC', 'short_description' => 'XAF', 'country' => 'Gabon', 'rate' => 0],
            ['currency' => 'Dalasi', 'short_description' => 'GMD', 'country' => 'Gambia (The)', 'rate' => 0],
            ['currency' => 'Lari', 'short_description' => 'GEL', 'country' => 'Georgia', 'rate' => 0],
            ['currency' => 'Euro', 'short_description' => 'EUR', 'country' => 'Germany', 'rate' => 0],
            ['currency' => 'Ghana Cedi', 'short_description' => 'GHS', 'country' => 'Ghana', 'rate' => 0],
            ['currency' => 'Gibraltar Pound', 'short_description' => 'GIP', 'country' => 'Gibraltar', 'rate' => 0],
            ['currency' => 'Euro', 'short_description' => 'EUR', 'country' => 'Greece', 'rate' => 0],
            ['currency' => 'Danish Krone', 'short_description' => 'DKK', 'country' => 'Greenland', 'rate' => 0],
            ['currency' => 'East Caribbean Dollar', 'short_description' => 'XCD', 'country' => 'Grenada', 'rate' => 0],
            ['currency' => 'Euro', 'short_description' => 'EUR', 'country' => 'Guadeloupe', 'rate' => 0],
            ['currency' => 'US Dollar', 'short_description' => 'USD', 'country' => 'Guam', 'rate' => 0],
            ['currency' => 'Quetzal', 'short_description' => 'GTQ', 'country' => 'Guatemala', 'rate' => 0],
            ['currency' => 'Pound Sterling', 'short_description' => 'GBP', 'country' => 'Guernsey', 'rate' => 0],
            ['currency' => 'Guinean Franc', 'short_description' => 'GNF', 'country' => 'Guinea', 'rate' => 0],
            ['currency' => 'CFA Franc BCEAO', 'short_description' => 'XOF', 'country' => 'Guinea-Bissau', 'rate' => 0],
            ['currency' => 'Guyana Dollar', 'short_description' => 'GYD', 'country' => 'Guyana', 'rate' => 0],
            ['currency' => 'Gourde', 'short_description' => 'HTG', 'country' => 'Haiti', 'rate' => 0],
            ['currency' => 'US Dollar', 'short_description' => 'USD', 'country' => 'Haiti', 'rate' => 0],
            ['currency' => 'Australian Dollar', 'short_description' => 'AUD', 'country' => 'Heard Island And Mcdonald Islands', 'rate' => 0],
            ['currency' => 'Euro', 'short_description' => 'EUR', 'country' => 'Holy See (The)', 'rate' => 0],
            ['currency' => 'Lempira', 'short_description' => 'HNL', 'country' => 'Honduras', 'rate' => 0],
            ['currency' => 'Hong Kong Dollar', 'short_description' => 'HKD', 'country' => 'Hong Kong', 'rate' => 0],
            ['currency' => 'Forint', 'short_description' => 'HUF', 'country' => 'Hungary', 'rate' => 0],
            ['currency' => 'Iceland Krona', 'short_description' => 'ISK', 'country' => 'Iceland', 'rate' => 0],
            ['currency' => 'Indian Rupee', 'short_description' => 'INR', 'country' => 'India', 'rate' => 0],
            ['currency' => 'Rupiah', 'short_description' => 'IDR', 'country' => 'Indonesia', 'rate' => 0],
            ['currency' => 'SDR (Special Drawing Right)', 'short_description' => 'XDR', 'country' => 'International Monetary Fund (Imf) ', 'rate' => 0],
            ['currency' => 'Iranian Rial', 'short_description' => 'IRR', 'country' => 'Iran (Islamic Republic Of)', 'rate' => 0],
            ['currency' => 'Iraqi Dinar', 'short_description' => 'IQD', 'country' => 'Iraq', 'rate' => 0],
            ['currency' => 'Euro', 'short_description' => 'EUR', 'country' => 'Ireland', 'rate' => 0],
            ['currency' => 'Pound Sterling', 'short_description' => 'GBP', 'country' => 'Isle Of Man', 'rate' => 0],
            ['currency' => 'New Israeli Sheqel', 'short_description' => 'ILS', 'country' => 'Israel', 'rate' => 0],
            ['currency' => 'Euro', 'short_description' => 'EUR', 'country' => 'Italy', 'rate' => 0],
            ['currency' => 'Jamaican Dollar', 'short_description' => 'JMD', 'country' => 'Jamaica', 'rate' => 0],
            ['currency' => 'Yen', 'short_description' => 'JPY', 'country' => 'Japan', 'rate' => 0],
            ['currency' => 'Pound Sterling', 'short_description' => 'GBP', 'country' => 'Jersey', 'rate' => 0],
            ['currency' => 'Jordanian Dinar', 'short_description' => 'JOD', 'country' => 'Jordan', 'rate' => 0],
            ['currency' => 'Tenge', 'short_description' => 'KZT', 'country' => 'Kazakhstan', 'rate' => 0],
            ['currency' => 'Kenyan Shilling', 'short_description' => 'KES', 'country' => 'Kenya', 'rate' => 0],
            ['currency' => 'Australian Dollar', 'short_description' => 'AUD', 'country' => 'Kiribati', 'rate' => 0],
            ['currency' => 'North Korean Won', 'short_description' => 'KPW', 'country' => 'Korea (The Democratic People’s Republic Of)', 'rate' => 0],
            ['currency' => 'Won', 'short_description' => 'KRW', 'country' => 'Korea (The Republic Of)', 'rate' => 0],
            ['currency' => 'Kuwaiti Dinar', 'short_description' => 'KWD', 'country' => 'Kuwait', 'rate' => 0],
            ['currency' => 'Som', 'short_description' => 'KGS', 'country' => 'Kyrgyzstan', 'rate' => 0],
            ['currency' => 'Lao Kip', 'short_description' => 'LAK', 'country' => 'Lao People’s Democratic Republic (The)', 'rate' => 0],
            ['currency' => 'Euro', 'short_description' => 'EUR', 'country' => 'Latvia', 'rate' => 0],
            ['currency' => 'Lebanese Pound', 'short_description' => 'LBP', 'country' => 'Lebanon', 'rate' => 0],
            ['currency' => 'Loti', 'short_description' => 'LSL', 'country' => 'Lesotho', 'rate' => 0],
            ['currency' => 'Rand', 'short_description' => 'ZAR', 'country' => 'Lesotho', 'rate' => 0],
            ['currency' => 'Liberian Dollar', 'short_description' => 'LRD', 'country' => 'Liberia', 'rate' => 0],
            ['currency' => 'Libyan Dinar', 'short_description' => 'LYD', 'country' => 'Libya', 'rate' => 0],
            ['currency' => 'Swiss Franc', 'short_description' => 'CHF', 'country' => 'Liechtenstein', 'rate' => 0],
            ['currency' => 'Euro', 'short_description' => 'EUR', 'country' => 'Lithuania', 'rate' => 0],
            ['currency' => 'Euro', 'short_description' => 'EUR', 'country' => 'Luxembourg', 'rate' => 0],
            ['currency' => 'Pataca', 'short_description' => 'MOP', 'country' => 'Macao', 'rate' => 0],
            ['currency' => 'Denar', 'short_description' => 'MKD', 'country' => 'Macedonia (The Former Yugoslav Republic Of)', 'rate' => 0],
            ['currency' => 'Malagasy Ariary', 'short_description' => 'MGA', 'country' => 'Madagascar', 'rate' => 0],
            ['currency' => 'Malawi Kwacha', 'short_description' => 'MWK', 'country' => 'Malawi', 'rate' => 0],
            ['currency' => 'Malaysian Ringgit', 'short_description' => 'MYR', 'country' => 'Malaysia', 'rate' => 0],
            ['currency' => 'Rufiyaa', 'short_description' => 'MVR', 'country' => 'Maldives', 'rate' => 0],
            ['currency' => 'CFA Franc BCEAO', 'short_description' => 'XOF', 'country' => 'Mali', 'rate' => 0],
            ['currency' => 'Euro', 'short_description' => 'EUR', 'country' => 'Malta', 'rate' => 0],
            ['currency' => 'US Dollar', 'short_description' => 'USD', 'country' => 'Marshall Islands (The)', 'rate' => 0],
            ['currency' => 'Euro', 'short_description' => 'EUR', 'country' => 'Martinique', 'rate' => 0],
            ['currency' => 'Ouguiya', 'short_description' => 'MRU', 'country' => 'Mauritania', 'rate' => 0],
            ['currency' => 'Mauritius Rupee', 'short_description' => 'MUR', 'country' => 'Mauritius', 'rate' => 0],
            ['currency' => 'Euro', 'short_description' => 'EUR', 'country' => 'Mayotte', 'rate' => 0],
            ['currency' => 'ADB Unit of Account', 'short_description' => 'XUA', 'country' => 'Member Countries Of The African Development Bank Group', 'rate' => 0],
            ['currency' => 'Mexican Peso', 'short_description' => 'MXN', 'country' => 'Mexico', 'rate' => 0],
            ['currency' => 'Mexican Unidad de Inversion (UDI)', 'short_description' => 'MXV', 'country' => 'Mexico', 'rate' => 0],
            ['currency' => 'US Dollar', 'short_description' => 'USD', 'country' => 'Micronesia (Federated States Of)', 'rate' => 0],
            ['currency' => 'Moldovan Leu', 'short_description' => 'MDL', 'country' => 'Moldova (The Republic Of)', 'rate' => 0],
            ['currency' => 'Euro', 'short_description' => 'EUR', 'country' => 'Monaco', 'rate' => 0],
            ['currency' => 'Tugrik', 'short_description' => 'MNT', 'country' => 'Mongolia', 'rate' => 0],
            ['currency' => 'Euro', 'short_description' => 'EUR', 'country' => 'Montenegro', 'rate' => 0],
            ['currency' => 'East Caribbean Dollar', 'short_description' => 'XCD', 'country' => 'Montserrat', 'rate' => 0],
            ['currency' => 'Moroccan Dirham', 'short_description' => 'MAD', 'country' => 'Morocco', 'rate' => 0],
            ['currency' => 'Mozambique Metical', 'short_description' => 'MZN', 'country' => 'Mozambique', 'rate' => 0],
            ['currency' => 'Kyat', 'short_description' => 'MMK', 'country' => 'Myanmar', 'rate' => 0],
            ['currency' => 'Namibia Dollar', 'short_description' => 'NAD', 'country' => 'Namibia', 'rate' => 0],
            ['currency' => 'Rand', 'short_description' => 'ZAR', 'country' => 'Namibia', 'rate' => 0],
            ['currency' => 'Australian Dollar', 'short_description' => 'AUD', 'country' => 'Nauru', 'rate' => 0],
            ['currency' => 'Nepalese Rupee', 'short_description' => 'NPR', 'country' => 'Nepal', 'rate' => 0],
            ['currency' => 'Euro', 'short_description' => 'EUR', 'country' => 'Netherlands (The)', 'rate' => 0],
            ['currency' => 'CFP Franc', 'short_description' => 'XPF', 'country' => 'New Caledonia', 'rate' => 0],
            ['currency' => 'New Zealand Dollar', 'short_description' => 'NZD', 'country' => 'New Zealand', 'rate' => 0],
            ['currency' => 'Cordoba Oro', 'short_description' => 'NIO', 'country' => 'Nicaragua', 'rate' => 0],
            ['currency' => 'CFA Franc BCEAO', 'short_description' => 'XOF', 'country' => 'Niger (The)', 'rate' => 0],
            ['currency' => 'Naira', 'short_description' => 'NGN', 'country' => 'Nigeria', 'rate' => 0],
            ['currency' => 'New Zealand Dollar', 'short_description' => 'NZD', 'country' => 'Niue', 'rate' => 0],
            ['currency' => 'Australian Dollar', 'short_description' => 'AUD', 'country' => 'Norfolk Island', 'rate' => 0],
            ['currency' => 'US Dollar', 'short_description' => 'USD', 'country' => 'Northern Mariana Islands (The)', 'rate' => 0],
            ['currency' => 'Norwegian Krone', 'short_description' => 'NOK', 'country' => 'Norway', 'rate' => 0],
            ['currency' => 'Rial Omani', 'short_description' => 'OMR', 'country' => 'Oman', 'rate' => 0],
            ['currency' => 'Pakistan Rupee', 'short_description' => 'PKR', 'country' => 'Pakistan', 'rate' => 0],
            ['currency' => 'US Dollar', 'short_description' => 'USD', 'country' => 'Palau', 'rate' => 0],
            ['currency' => 'Balboa', 'short_description' => 'PAB', 'country' => 'Panama', 'rate' => 0],
            ['currency' => 'US Dollar', 'short_description' => 'USD', 'country' => 'Panama', 'rate' => 0],
            ['currency' => 'Kina', 'short_description' => 'PGK', 'country' => 'Papua New Guinea', 'rate' => 0],
            ['currency' => 'Guarani', 'short_description' => 'PYG', 'country' => 'Paraguay', 'rate' => 0],
            ['currency' => 'Sol', 'short_description' => 'PEN', 'country' => 'Peru', 'rate' => 0],
            ['currency' => 'Philippine Peso', 'short_description' => 'PHP', 'country' => 'Philippines (The)', 'rate' => 0],
            ['currency' => 'New Zealand Dollar', 'short_description' => 'NZD', 'country' => 'Pitcairn', 'rate' => 0],
            ['currency' => 'Zloty', 'short_description' => 'PLN', 'country' => 'Poland', 'rate' => 0],
            ['currency' => 'Euro', 'short_description' => 'EUR', 'country' => 'Portugal', 'rate' => 0],
            ['currency' => 'US Dollar', 'short_description' => 'USD', 'country' => 'Puerto Rico', 'rate' => 0],
            ['currency' => 'Qatari Rial', 'short_description' => 'QAR', 'country' => 'Qatar', 'rate' => 0],
            ['currency' => 'Euro', 'short_description' => 'EUR', 'country' => 'Réunion', 'rate' => 0],
            ['currency' => 'Romanian Leu', 'short_description' => 'RON', 'country' => 'Romania', 'rate' => 0],
            ['currency' => 'Russian Ruble', 'short_description' => 'RUB', 'country' => 'Russian Federation (The)', 'rate' => 0],
            ['currency' => 'Rwanda Franc', 'short_description' => 'RWF', 'country' => 'Rwanda', 'rate' => 0],
            ['currency' => 'Euro', 'short_description' => 'EUR', 'country' => 'Saint Barthélemy', 'rate' => 0],
            ['currency' => 'Saint Helena Pound', 'short_description' => 'SHP', 'country' => 'Saint Helena, Ascension And Tristan Da Cunha', 'rate' => 0],
            ['currency' => 'East Caribbean Dollar', 'short_description' => 'XCD', 'country' => 'Saint Kitts And Nevis', 'rate' => 0],
            ['currency' => 'East Caribbean Dollar', 'short_description' => 'XCD', 'country' => 'Saint Lucia', 'rate' => 0],
            ['currency' => 'Euro', 'short_description' => 'EUR', 'country' => 'Saint Martin (French Part)', 'rate' => 0],
            ['currency' => 'Euro', 'short_description' => 'EUR', 'country' => 'Saint Pierre And Miquelon', 'rate' => 0],
            ['currency' => 'East Caribbean Dollar', 'short_description' => 'XCD', 'country' => 'Saint Vincent And The Grenadines', 'rate' => 0],
            ['currency' => 'Tala', 'short_description' => 'WST', 'country' => 'Samoa', 'rate' => 0],
            ['currency' => 'Euro', 'short_description' => 'EUR', 'country' => 'San Marino', 'rate' => 0],
            ['currency' => 'Dobra', 'short_description' => 'STN', 'country' => 'Sao Tome And Principe', 'rate' => 0],
            ['currency' => 'Saudi Riyal', 'short_description' => 'SAR', 'country' => 'Saudi Arabia', 'rate' => 0],
            ['currency' => 'CFA Franc BCEAO', 'short_description' => 'XOF', 'country' => 'Senegal', 'rate' => 0],
            ['currency' => 'Serbian Dinar', 'short_description' => 'RSD', 'country' => 'Serbia', 'rate' => 0],
            ['currency' => 'Seychelles Rupee', 'short_description' => 'SCR', 'country' => 'Seychelles', 'rate' => 0],
            ['currency' => 'Leone', 'short_description' => 'SLL', 'country' => 'Sierra Leone', 'rate' => 0],
            ['currency' => 'Singapore Dollar', 'short_description' => 'SGD', 'country' => 'Singapore', 'rate' => 0],
            ['currency' => 'Netherlands Antillean Guilder', 'short_description' => 'ANG', 'country' => 'Sint Maarten (Dutch Part)', 'rate' => 0],
            ['currency' => 'Sucre', 'short_description' => 'XSU', 'country' => 'Sistema Unitario De Compensacion Regional De Pagos "Sucre"', 'rate' => 0],
            ['currency' => 'Euro', 'short_description' => 'EUR', 'country' => 'Slovakia', 'rate' => 0],
            ['currency' => 'Euro', 'short_description' => 'EUR', 'country' => 'Slovenia', 'rate' => 0],
            ['currency' => 'Solomon Islands Dollar', 'short_description' => 'SBD', 'country' => 'Solomon Islands', 'rate' => 0],
            ['currency' => 'Somali Shilling', 'short_description' => 'SOS', 'country' => 'Somalia', 'rate' => 0],
            ['currency' => 'Rand', 'short_description' => 'ZAR', 'country' => 'South Africa', 'rate' => 0],
            ['currency' => 'South Sudanese Pound', 'short_description' => 'SSP', 'country' => 'South Sudan', 'rate' => 0],
            ['currency' => 'Euro', 'short_description' => 'EUR', 'country' => 'Spain', 'rate' => 0],
            ['currency' => 'Sri Lanka Rupee', 'short_description' => 'LKR', 'country' => 'Sri Lanka', 'rate' => 0],
            ['currency' => 'Sudanese Pound', 'short_description' => 'SDG', 'country' => 'Sudan (The)', 'rate' => 0],
            ['currency' => 'Surinam Dollar', 'short_description' => 'SRD', 'country' => 'Suriname', 'rate' => 0],
            ['currency' => 'Norwegian Krone', 'short_description' => 'NOK', 'country' => 'Svalbard And Jan Mayen', 'rate' => 0],
            ['currency' => 'Lilangeni', 'short_description' => 'SZL', 'country' => 'Eswatini', 'rate' => 0],
            ['currency' => 'Swedish Krona', 'short_description' => 'SEK', 'country' => 'Sweden', 'rate' => 0],
            ['currency' => 'Swiss Franc', 'short_description' => 'CHF', 'country' => 'Switzerland', 'rate' => 0],
            ['currency' => 'WIR Euro', 'short_description' => 'CHE', 'country' => 'Switzerland', 'rate' => 0],
            ['currency' => 'WIR Franc', 'short_description' => 'CHW', 'country' => 'Switzerland', 'rate' => 0],
            ['currency' => 'Syrian Pound', 'short_description' => 'SYP', 'country' => 'Syrian Arab Republic', 'rate' => 0],
            ['currency' => 'New Taiwan Dollar', 'short_description' => 'TWD', 'country' => 'Taiwan (Province Of China)', 'rate' => 0],
            ['currency' => 'Somoni', 'short_description' => 'TJS', 'country' => 'Tajikistan', 'rate' => 0],
            ['currency' => 'Tanzanian Shilling', 'short_description' => 'TZS', 'country' => 'Tanzania, United Republic Of', 'rate' => 0],
            ['currency' => 'Baht', 'short_description' => 'THB', 'country' => 'Thailand', 'rate' => 0],
            ['currency' => 'US Dollar', 'short_description' => 'USD', 'country' => 'Timor-Leste', 'rate' => 0],
            ['currency' => 'CFA Franc BCEAO', 'short_description' => 'XOF', 'country' => 'Togo', 'rate' => 0],
            ['currency' => 'New Zealand Dollar', 'short_description' => 'NZD', 'country' => 'Tokelau', 'rate' => 0],
            ['currency' => 'Pa’anga', 'short_description' => 'TOP', 'country' => 'Tonga', 'rate' => 0],
            ['currency' => 'Trinidad and Tobago Dollar', 'short_description' => 'TTD', 'country' => 'Trinidad And Tobago', 'rate' => 0],
            ['currency' => 'Tunisian Dinar', 'short_description' => 'TND', 'country' => 'Tunisia', 'rate' => 0],
            ['currency' => 'Turkish Lira', 'short_description' => 'TRY', 'country' => 'Turkey', 'rate' => 0],
            ['currency' => 'Turkmenistan New Manat', 'short_description' => 'TMT', 'country' => 'Turkmenistan', 'rate' => 0],
            ['currency' => 'US Dollar', 'short_description' => 'USD', 'country' => 'Turks And Caicos Islands (The)', 'rate' => 0],
            ['currency' => 'Australian Dollar', 'short_description' => 'AUD', 'country' => 'Tuvalu', 'rate' => 0],
            ['currency' => 'Uganda Shilling', 'short_description' => 'UGX', 'country' => 'Uganda', 'rate' => 0],
            ['currency' => 'Hryvnia', 'short_description' => 'UAH', 'country' => 'Ukraine', 'rate' => 0],
            ['currency' => 'UAE Dirham', 'short_description' => 'AED', 'country' => 'United Arab Emirates (The)', 'rate' => 0],
            ['currency' => 'Pound Sterling', 'short_description' => 'GBP', 'country' => 'United Kingdom Of Great Britain And Northern Ireland (The)', 'rate' => 0],
            ['currency' => 'US Dollar', 'short_description' => 'USD', 'country' => 'United States Minor Outlying Islands (The)', 'rate' => 0],
            ['currency' => 'US Dollar', 'short_description' => 'USD', 'country' => 'United States Of America (The)', 'rate' => 0],
            ['currency' => 'US Dollar (Next day)', 'short_description' => 'USN', 'country' => 'United States Of America (The)', 'rate' => 0],
            ['currency' => 'Peso Uruguayo', 'short_description' => 'UYU', 'country' => 'Uruguay', 'rate' => 0],
            ['currency' => 'Uruguay Peso en Unidades Indexadas (UI)', 'short_description' => 'UYI', 'country' => 'Uruguay', 'rate' => 0],
            ['currency' => 'Unidad Previsional', 'short_description' => 'UYW', 'country' => 'Uruguay', 'rate' => 0],
            ['currency' => 'Uzbekistan Sum', 'short_description' => 'UZS', 'country' => 'Uzbekistan', 'rate' => 0],
            ['currency' => 'Vatu', 'short_description' => 'VUV', 'country' => 'Vanuatu', 'rate' => 0],
            ['currency' => 'Bolívar Soberano', 'short_description' => 'VES', 'country' => 'Venezuela (Bolivarian Republic Of)', 'rate' => 0],
            ['currency' => 'Dong', 'short_description' => 'VND', 'country' => 'Viet Nam', 'rate' => 0],
            ['currency' => 'US Dollar', 'short_description' => 'USD', 'country' => 'Virgin Islands (British)', 'rate' => 0],
            ['currency' => 'US Dollar', 'short_description' => 'USD', 'country' => 'Virgin Islands (U.S.)', 'rate' => 0],
            ['currency' => 'CFP Franc', 'short_description' => 'XPF', 'country' => 'Wallis And Futuna', 'rate' => 0],
            ['currency' => 'Moroccan Dirham', 'short_description' => 'MAD', 'country' => 'Western Sahara', 'rate' => 0],
            ['currency' => 'Yemeni Rial', 'short_description' => 'YER', 'country' => 'Yemen', 'rate' => 0],
            ['currency' => 'Zambian Kwacha', 'short_description' => 'ZMW', 'country' => 'Zambia', 'rate' => 0],
            ['currency' => 'Zimbabwe Dollar', 'short_description' => 'ZWL', 'country' => 'Zimbabwe', 'rate' => 0],
            ['currency' => 'Bond Markets Unit European Composite Unit (EURCO)', 'short_description' => 'XBA', 'country' => 'Zz01_Bond Markets Unit European_Eurco', 'rate' => 0],
            ['currency' => 'Bond Markets Unit European Monetary Unit (E.M.U.-6)', 'short_description' => 'XBB', 'country' => 'Zz02_Bond Markets Unit European_Emu-6', 'rate' => 0],
            ['currency' => 'Bond Markets Unit European Unit of Account 9 (E.U.A.-9)', 'short_description' => 'XBC', 'country' => 'Zz03_Bond Markets Unit European_Eua-9', 'rate' => 0],
            ['currency' => 'Bond Markets Unit European Unit of Account 17 (E.U.A.-17)', 'short_description' => 'XBD', 'country' => 'Zz04_Bond Markets Unit European_Eua-17', 'rate' => 0],
            ['currency' => 'Codes specifically reserved for testing purposes', 'short_description' => 'XTS', 'country' => 'Zz06_Testing_Code', 'rate' => 0],
            ['currency' => 'The codes assigned for transactions where no currency is involved', 'short_description' => 'XXX', 'country' => 'Zz07_No_Currency', 'rate' => 0],
            ['currency' => 'Gold', 'short_description' => 'XAU', 'country' => 'Zz08_Gold', 'rate' => 0],
            ['currency' => 'Palladium', 'short_description' => 'XPD', 'country' => 'Zz09_Palladium', 'rate' => 0],
            ['currency' => 'Platinum', 'short_description' => 'XPT', 'country' => 'Zz10_Platinum', 'rate' => 0],
            ['currency' => 'Silver', 'short_description' => 'XAG', 'country' => 'Zz11_Silver', 'rate' => 0],
        ]);
    }
}
