<?php

namespace App\Http\Controllers;

use App\AppFeedback;
use App\Http\Resources\AppFeedbackResource;
use Illuminate\Http\Request;

class AppFeedbackController extends BaseController
{
    public function __construct($model = AppFeedback::class, $resource = AppFeedbackResource::class)
    {
        parent::__construct($model, $resource);
    }

    /**
     * @SWG\Get(
     *   path="/feedback",
     *   tags={"Feedback"},
     *   summary="App feedbacks",
     *  security={
     *     {"bearer": {}},
     *   },
     *   @SWG\Response(response=200, description="Success"),
     *   @SWG\Response(response=400, description="Not found"),
     *   @SWG\Response(response=500, description="internal server error")
     * )
     */

    /**
     * @SWG\Post(
     *   path="/feedback",
     *   tags={"Feedback"},
     *   summary="Create App feedback",
     *  security={
     *     {"bearer": {}},
     *   },
     *   @SWG\Parameter(name="feedback",in="query",description="feedback",required=true,type="string"),
     *   @SWG\Response(response=200, description="Success"),
     *   @SWG\Response(response=400, description="Not found"),
     *   @SWG\Response(response=500, description="internal server error")
     * )
     */

    public function store(Request $request)
    {
        $request->merge(['user_id' => $request->user()->id]);
        return parent::store($request); // TODO: Change the autogenerated stub
    }

    /**
     * @SWG\Get(
     *   path="/feedback/{id}",
     *   tags={"Feedback"},
     *   summary="Retrieve App Feedback",
     *  security={
     *     {"bearer": {}},
     *   },
     *   @SWG\Parameter(name="id",in="path",description="feedback id",required=true,type="integer"),
     *   @SWG\Response(response=200, description="Success"),
     *   @SWG\Response(response=400, description="Not found"),
     *   @SWG\Response(response=500, description="internal server error")
     * )
     */
}
